package src;

import src.StarRater;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class AddAlbumForm {

    private static int selection;
    private JTextField titreTextField;
    private JTextField langueTextField;
    private JTextField auteurTextField;
    private JTextField duréeTextField;
    private JCheckBox checkBox1;
    private JTextField dateDeSortieTextField;
    private JTextField genreTextField;
    private JTextField supportTextField;
    private JTextArea commentaireTextArea;
    private JPanel panel4;
    private JButton button1;
    private StarRater starRater1;

    public static void main(String[] args) {
        JFrame Frame = new JFrame();
        Frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Frame.setContentPane(new AddAlbumForm().panel4);
        Frame.setVisible(true);
        Frame.setSize(600, 600);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        titreTextField = new JTextField();
        titreTextField.setText("Titre");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(titreTextField, gbc);
        langueTextField = new JTextField();
        langueTextField.setText("Langue");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(langueTextField, gbc);
        auteurTextField = new JTextField();
        auteurTextField.setText("Auteur");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(auteurTextField, gbc);
        duréeTextField = new JTextField();
        duréeTextField.setText("Durée");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(duréeTextField, gbc);
        genreTextField = new JTextField();
        genreTextField.setText("Genre");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(genreTextField, gbc);
        commentaireTextArea = new JTextArea();
        commentaireTextArea.setText("Commentaire");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.gridheight = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel4.add(commentaireTextArea, gbc);
        button1 = new JButton();
        button1.setText("Button");
        button1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String supportgetText = supportTextField.getText();
                String titregetText = titreTextField.getText();
                String genregetText = genreTextField.getText();
                String commentairegetText = commentaireTextArea.getText();
                String auteurgetText = auteurTextField.getText();
                String languegetText = langueTextField.getText();
                String datesortiegetText = dateDeSortieTextField.getText();
                String dureegetText = duréeTextField.getText();
                boolean statutgetBox = checkBox1.isSelected();
                int starrater = selection;
                System.out.println(supportgetText + "." + titregetText + "." + genregetText + "." + statutgetBox + "." + starrater);

                src.DtbGestion.Dtbinsert.insert("SELECT * FROM Oeuvres");

            }
        });
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(button1, gbc);
        starRater1 = new StarRater();
        starRater1.addStarListener(
                new StarRater.StarListener()   {

                    public void handleSelection(int selection) {
                        System.out.println(selection);
                        AddAlbumForm.selection= selection;
                    }
                });
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        panel4.add(starRater1, gbc);
        supportTextField = new JTextField();
        supportTextField.setText("Support");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(supportTextField, gbc);
        dateDeSortieTextField = new JTextField();
        dateDeSortieTextField.setText("Date de sortie");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(dateDeSortieTextField, gbc);
        checkBox1 = new JCheckBox();
        checkBox1.setText("CheckBox");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel4.add(checkBox1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel4;
    }
}
