package src;

import javax.swing.*;
import java.awt.*;

public class AddForm extends Container {
    private JPanel panel1;
    private JCheckBox statutCheckBox;
    private JTextArea commentaireTextArea;
    private JTextField titreTextField;
    private JButton button1;
    private JTextField genreTextField;
    private JTextField auteurTextField;
    private JTextField supportTextField;
    private JTextField langueTextField;
    private JTextField origineTextField;
    private JFormattedTextField a1999FormattedTextField;
    private JTextField duréeTextField;


    public static void main(String[] args) {
        JFrame Frame = new JFrame();
        Frame.setContentPane(new AddForm().panel1);
        Frame.setVisible(true);
        Frame.setSize(600, 600);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        button1 = new JButton();
        button1.setText("Button");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(button1, gbc);
        supportTextField = new JTextField();
        supportTextField.setText("Support");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(supportTextField, gbc);
        titreTextField = new JTextField();
        titreTextField.setText("Titre");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(titreTextField, gbc);
        genreTextField = new JTextField();
        genreTextField.setText("Genre");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(genreTextField, gbc);
        statutCheckBox = new JCheckBox();
        statutCheckBox.setText("Statut");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(statutCheckBox, gbc);
        origineTextField = new JTextField();
        origineTextField.setText("Origine");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(origineTextField, gbc);
        langueTextField = new JTextField();
        langueTextField.setText("Langue");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(langueTextField, gbc);
        a1999FormattedTextField = new JFormattedTextField();
        a1999FormattedTextField.setText("1999");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(a1999FormattedTextField, gbc);
        commentaireTextArea = new JTextArea();
        commentaireTextArea.setText("Commentaire");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.gridheight = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(commentaireTextArea, gbc);
        auteurTextField = new JTextField();
        auteurTextField.setText("Auteur");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(auteurTextField, gbc);
        final StarRater starRater1 = new StarRater();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        panel1.add(starRater1, gbc);
        duréeTextField = new JTextField();
        duréeTextField.setText("Durée");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(duréeTextField, gbc);

    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}