package src;

import src.StarRater;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class AddJeuxForm extends Container {

    private static int selection;
    private JPanel panel2;
    private JTextField titreTextField;
    private JTextField origineTextField;
    private JTextField consoleTextField;
    private JTextField dateDeSortieTextField;
    private JTextField nbJoueurTextField;
    private JTextField pegiTextField;
    private JCheckBox checkBox1;
    private JTextField langueTextField1;
    private JTextField genreTextField;
    private JTextArea commentaireTextArea;
    private JButton button1;
    private StarRater starRater1;

    public static void main(String[] args) {
        JFrame Frame = new JFrame();
        Frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Frame.setContentPane(new AddJeuxForm().panel2);
        Frame.setVisible(true);
        Frame.setSize(600, 600);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        consoleTextField = new JTextField();
        consoleTextField.setText("Console");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(consoleTextField, gbc);
        nbJoueurTextField = new JTextField();
        nbJoueurTextField.setText("NbJoueur");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(nbJoueurTextField, gbc);
        genreTextField = new JTextField();
        genreTextField.setText("Genre");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(genreTextField, gbc);
        dateDeSortieTextField = new JTextField();
        dateDeSortieTextField.setText("Date de sortie");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(dateDeSortieTextField, gbc);
        origineTextField = new JTextField();
        origineTextField.setText("Origine");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(origineTextField, gbc);
        commentaireTextArea = new JTextArea();
        commentaireTextArea.setText("Commentaire");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.gridheight = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel2.add(commentaireTextArea, gbc);
        button1 = new JButton();
        button1.setText("Button");
        button1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //String supportgetText = supportTextField.getText();
                String titregetText = titreTextField.getText();
                String genregetText = genreTextField.getText();
                String commentairegetText = commentaireTextArea.getText();
                //String auteurgetText = auteurTextField.getText();
                //String languegetText = langueTextField.getText();
                String originegetText = origineTextField.getText();
                //String dategetText = a1999FormattedTextField.getText();
                //String dureegetText = dureeTextField.getText();
                //boolean statutgetBox = statutCheckBox.isSelected();
                int starrater = selection;
                //System.out.println(supportgetText + "." + titregetText + "." + genregetText + "." + statutgetBox + "." + starrater);

                //src.DtbGestion.Dtbinsert.insert();

            }
        });
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(button1, gbc);
        starRater1 = new StarRater();
        starRater1.addStarListener(
                new StarRater.StarListener()   {

                    public void handleSelection(int selection) {
                        System.out.println(selection);
                        AddJeuxForm.selection= selection;
                    }
                });
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        panel2.add(starRater1, gbc);
        pegiTextField = new JTextField();
        pegiTextField.setText("Pegi");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(pegiTextField, gbc);
        checkBox1 = new JCheckBox();
        checkBox1.setText("CheckBox");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(checkBox1, gbc);
        langueTextField1 = new JTextField();
        langueTextField1.setText("Langue");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(langueTextField1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel2;
    }
}
